<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<ul class = "heading-slide-product">
    <li><h2><?php echo $this->__('Sản phẩm khuyến mãi') ?></h2></li>
    <li><a href="#"> Xem tất cả </a></li>
</ul>

<div class="category-products">
    <?php //echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        	<?php $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
				if ($specialprice){?>
				 	<div class="label-sale">
				   	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
				   		<img src="<?php echo $this->getSkinUrl('images/') ?>label-sale.png" />
				   	</a>
				   </div> 
			<?php } ?>
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180); ?>" width="180" height="180" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
	
    <?php 
	$json_str = '{"owl": [';

	foreach ($_productCollection as $_product):

	$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();

        if ($specialprice){

	$phrase1 = '<div class="label-sale">
	<a href="'. $_product->getProductUrl().'" title="'.$this->htmlEscape($_product->getName()).'">
		<img src="'.$this->getSkinUrl('images/').'label-sale.png" />
	</a>
	</div>';
	}else{
            $phrase1 = "";
        }
	?>
	<?php 
	$phrase2 = 
	'<a href="'.$_product->getProductUrl().'" title="'.$this->stripTags($_product->getName(), null, true).'" class="product-image">
	<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(160).'" alt="'.$this->stripTags($_product->getName(), null, true) .'" />
	</a>';	
    ?>
	<?php
	$phrase3 =
	'<h3 class="product-name"><a href="'.$_product->getProductUrl().'" title="'.$this->stripTags($_product->getName(), null, true).'">'.$this->helper('catalog/output')->productAttribute($_product, $_product->getName() , "name").'</a>
	</h3>';	
	?>
	<?php
	$phrase4 = $this->getPriceHtml($_product, true);
	
	?>
	
	<?php
	if ($_product->isSaleable()){
		$phrase5 = 
		'<a href="'.$_product->getProductUrl().'"><button type="button" title="'.$this->__('Add to Cart').'" class="button btn-cart"><span><span>'.$this->__('Add to Cart').'</span></span></button></a>';
	} else{
		$phrase5 =
		'<p class="availability out-of-stock"><span>'.$this->__('Out of stock').'</span></p>';
	} 	
	?>
	
<?php
$str = <<<EOF
<li class="item">$phrase1$phrase2$phrase3<div class="item-bottom">$phrase4
<div class="actions">
	$phrase5							
</div>
</div>
</li>
EOF;
?>
        <?php

		$str = preg_replace("/\r\n+|\r+|\n+|\t+/i", "", $str);
        $json_str .= "{ 'item' : '".$str."'},";
		endforeach;
        $json_str = rtrim($json_str,',');
		$json_str .= ']}';
		?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    
</div>
<?php endif; ?>

<ul id="sales-off" class="products-grid"></ul>
<script type="text/javascript" >
     jQuery(document).ready(function() {

         var owl_save = jQuery("#sales-off");

         owl_save.owlCarousel({
          jsonInput : <?php echo $json_str;?>
         });
    });
</script>
