<style>
    #brands .item{
		margin:3px;
        max-width: 300px;
	}
    #brands .item img{
		display:block;
		width:100%;
		height:auto;
	}
</style>

<div id="brands">
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/titan-logo.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/Tissot_logo_sport.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/citizen.png" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/casio-logo-01.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/9c58fb6bf5a11aaee3725de890e07483.jpeg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/skagen-logo.jpg" height="160" width="320" /></div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {

        jQuery("#brands").owlCarousel({

            autoPlay: 3000,
            items : 4,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3]
      });

    });
</script>
 
