<style>
    #brands .item{
		margin:3px;
        width: 320px;
        height: 160px;
	}
    #brands .item img{
		display:block;
		width:100%;
		height:auto;
	}
</style>

<div id="brands">
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/titan-logo.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/Tissot_logo_sport.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/citizen.png" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/casio-logo-01.jpg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/9c58fb6bf5a11aaee3725de890e07483.jpeg" height="160" width="320" /></div>
    <div class="item"><img alt="Owl Image" src="http://localhost/watchshop/media/wysiwyg/skagen-logo.jpg" height="160" width="320" /></div>
</div>
<div class="customNavigation">
    <a class="btn prev">Previous</a>
    <a class="btn next">Next</a>
    <a class="btn play">Autoplay</a>
    <a class="btn stop">Stop</a>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {

        var owl = jQuery("#brands");

        owl.owlCarousel({

            autoPlay: 3000,
            items : 4,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3]
        });

        // Custom Navigation Events
        jQuery(".next").click(function(){
            owl.trigger('owl.next');
        })
        jQuery(".prev").click(function(){
            owl.trigger('owl.prev');
        })
        jQuery(".play").click(function(){
            owl.trigger('owl.play',3000); //owl.play event accept autoPlay speed as second parameter
        })
        jQuery(".stop").click(function(){
            owl.trigger('owl.stop');
        })

    });
</script>
 
