<?php
/***************************************************************************
	@extension	: Bestseller Product.
	@copyright	: Copyright (c) 2015 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/
?>
<style>
.productList { float:left; width:720px; }
.productList .product { background:#fff; border:1px solid #ccc; padding:5px;  float:left; margin:10px 8px 10px 0; text-align:center; }
.productList .product .cl { padding:0 0 0 0px; text-align:center;}
.productList .product .prodDetails {text-align:center; padding:0 0 0 0px;  }
.productList .product .addCompare { text-align:center;  clear:both; }
.productList .product .addWishlist {clear:both; text-align:center; }
</style>
<?php
	$result = array();
	$pro = array();
	$bestseller_collection = $this->getBestsellerProduct();
	foreach($bestseller_collection as $collection){
		$pro[] = $collection->getEntityId();
	}
    if($this->getChooseProducts() == "1") {
		$result = $pro;
	}elseif($this->getChooseProducts() == "2") {
	   $result = $this->getProductIds();
	}else{
		if($this->getSortOrder() == 1){
			$result = array_unique(array_merge($pro, $this->getProductIds()));
		}elseif($this->getSortOrder() == 2){
			$result = array_unique(array_merge($this->getProductIds(),$pro));
		}else{
			$result = array_unique(array_merge($pro, $this->getProductIds()));
			shuffle($result);
		}
	}
	$upperLimit = ($this->getLimit()) ? $this->getLimit() : 1; 
	$itemPerRow = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 1 ;
	$products_price = $this->getProductsPrice();  
	$review = $this->getReview();
?>
<?php if($this->getEnabled()): ?>
<?php if($this->getHeader()): ?>

<div class="sectionHead"><h2><?php if(count($result) > 0) { echo $this->getHeader(); } ?></h2></div>
 <?php endif; ?>
	<div class="category-products">  
		<?php echo $this->getPagerHtml() ?>
		<ul class="products-grid">
        <?php
		$i=0; $x = 1;
		foreach($result as $result){
			$_product = $this->getProducts($result);
			if(!$_product){
				continue;
			}
			if($x <= $upperLimit)  {
				if($i++%$itemPerRow==0)
					echo '<ul class="products-grid">';
		?>
			<li class="item<?php if(($i-1)%$itemPerRow==0): ?> first<?php elseif($i%$itemPerRow==0): ?> last<?php endif; ?>">
				
					<a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 160,($this->getImageWidth()) ? $this->getImageWidth() : 160); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
					</a>
				
					<h3 class="product-name">
						<a href="<?php echo $this->getBaseUrl().$_product['url_path'] ?>" title="<?php echo $this->htmlEscape($_product['name']) ?>">
							<?php echo $this->htmlEscape($_product['name']) ?>
						</a>
					</h3>
				<div class="item-bottom">
					
						<?php 						    
							if($products_price == 1) {
								$_product = Mage::getModel('catalog/product')->load($_product->getId());
								echo $this->getPriceHtml($_product, true); 
							}
						?>                
				
					<div class="actions">
						<?php 					
							$addtocartval = $this->getAddToCart();
							if($addtocartval == 1){
								if($_product->isSaleable()): ?>
									<button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
								<?php else: ?>
									<span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>
								<?php endif; 
							} ?>
					</div>
				
				
			</div>
			</li>
		    <?php
				if(($i%$itemPerRow==0)||($i==$upperLimit)){ 
					echo '</ul>';
				}
			}
			$x++;
		} 
		?>
        
	</div>
 <?php endif; ?>